--- 
author: 3n
website: http://www.iancollins.me
contact: ian.collins@gmail.com
scripts: 
- MTCore
- MTSwipeEvent
- MTTapEvent
- MTPoint
- MTTranslate
- MTScrollView
tags: 
- mobile
- ios
- iphone
- ipad
current: 0.1
demo: http://iancollins.me/MooTouch-Demo/
name: MooTouch
