name: "MooTouch"

exports: "mootouch.js"

web: "[iancollins.me](http://www.iancollins.me)"

description: "A small framework for doing cool things with MooTools on touch-enabled devices."

license: "[MIT License](http://mootools.net/license.txt)"

copyright: "&copy; [Ian Collins](ian.collins@gmail.com)"

author: "3n"
authors: "[Ian Collins](http://www.iancollins.me) [Christoph Pojer](http://cpojer.net)"

sources:
    - "Source/MTPoint.js"
    - "Source/MTScrollView.js"
